language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl
    - LISP=ecl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

script:
  - cl -l fiveam
       -e '(setf fiveam:*on-error* :debug
                 fiveam:*on-failure* :debug)'
       -e '(setf *debugger-hook*
                 (lambda (car cdr)
                   (declare (ignore car cdr))
                   (uiop:quit -1)))'
       -e '(asdf:load-system :parsimony)'
       -e '(asdf:test-system :parsimony)'

notifications:
  email:
    - jacksonhodonnell@gmail.com
